extends Node2D


# Declare member variables here. Examples:
# var a = 2
# var b = "text"

var bogdan_pos = 0
var dialogue
var dialogue_ru
var dialogue_en
var dialogue_uk
func _ready():
	print("scene loaded")
	
	dialogue_ru = [
		"2018, 24 декабря 9:00|G",
		"Тёмыч: *Зевок*|Y|-|PLAY intro_1",
		"(Я проснулся в шесть.)|B",
		"(ЗАЧЕМ?!)",
		"(Как бы то ни было...)",
		"(Блин, сейчас середина зимы, зачем собирать конкурс гитаристов именно сейчас?)",
		"(Лично я считаю свою гитару пуленепроницаемой, холодом-не-расстраиваемой)",
		"(Но абсолютно все считают, что если гитару подвергнуть холоду, то она испортится)",
		"(Так если так, то зачем собирать конкурс гитаристов? Это такая тактика по 'уничтожению гитар' у Запорских гитарастов?)",
		"(...Как бы то ни было...)",
		"(Меня зовут Артём Зинец Артёмович, я из 6-Г класса в Лицее №99)",
		"(Который часто путают с ЗМЛ №99)",
		"(Школой по соседству такой...)",
		"(Я - гитарист с *уникальными* способностями)",
		"(Я не только играл произведения на три класса старше меня)",
		"(Но и--)|B|-|STOP",
		"???: Привет, капитан!|W|Lenich default",
		"Тёмыч: А, да, привет, давно не виделись...|W|Lenich default|PLAY lenich_theme",
		"???: Чё, как дела?",
		"Тёмыч: Та норм всё, вроде как...",
		"Да...",
		"(Это - Лёныч, мой друг и напарник с гитары.)|B",
		"(Мы играем в дуэте, вместе ездим на конкурсы по гитаре в самые разные города)",
		"(Исколесили половину всей страны на гастролях...)",
		"(Школьная жизнь веселая, только если эта школа - музыкалка.)",
		"(Он фанат полиции. Почти как Егогорыч.)",
		"(Только Егогорыч всё-таки фанат самой армии, в большинстве своём.)",
		"Лёныч: Эй, Тёмыч|W",
		"Ты че, не выспался, что ли?",
		"Тёмыч: (Хрен ты угадал...)|B",
		"Лёныч: Ты за это время успел хоть что-то хоть как-то сыграть?|W",
		"Я за эти 2 дня особо подготовиться не успел.",
		"Тёмыч: Ну, так как у нас было одинаково *не* было времени",
		"То я в такой же степени",
		"*Не* подготовился.",
		"(Гыг)|B",
		"Лёныч: Ты гитару там не забыл?|W",
		"Тёмыч: Вообще эта *бандура* прямо за спиной у меня висит",
		"Так что нет.",
		"Лёныч",
		"Лёныч: Шо",
		"Тёмыч: А че ты ел на завтрак?",
		"Лёныч: Эхех, котле-е-етки...",
		"Тёмыч: С пюрешкой?",
		"(Не по канону иду, но пофиг)|B",
		"Лёныч: И с хлебушком...!|W",
		"Тёмыч: Беленьким?",
		"Лёныч: Нет, с сееееереньким,",
		"Сееееереньким!",
		"Тёмыч: (Шо мы творим, ё-маё)|B",
		"(Шуточки за 300...)",
		"Тёмыч: Хобана, лимузин подъехал.|W",
		"Лёныч: Автобус, которым людей на конкурс гитарный повезут, приехал",
		"Но сама Ирина Николаевна не появилась как-то...",
		"Тёмыч: Странно, а че танцоры пришли",
		"Разве это не конкурс гитаристов?",
		"Лёныч: Может, это конкурс школ искусств.",
		"Для всех, типа",
		"Тёмыч: По всей видимости.",
		"Ладно, запрыгиваем, что уж...",
		"*Позже*|G|-|STOP STOP",
		"Тёмыч: Мы едем, едем, в соседнее село, на дискотекуууууууу\nЛёныч: В днепр.|W",
		"Тёмыч: Тра-ля-ля\nЛёныч: Тра-ля-ля-ля-ля-ляяяяяяяяя",
		"Тёмыч: (Я не спал целую неделю)|B",
		"(Буквально позавчера закончилась та неделя)",
		"(На которой на меня охотились коты и учителя)",
		"(Вынуждая меня не спать нормально больше недели)",
		"(Я ХОЧУ СПАТТТТТТТТТТТТТТ)",
		"(АААААААААА)",
		"*хрр*|Y",
		"Лёныч: Тёмыч? Не спи. Ау. Тьоха?|W",
		"Тёмыч: хрр....",
		"13 часов дня. Сон Тьохи|B",
		"Тёмыч: Изыдите, черти позорные!|W",
		"Ни сейчас, ни потом, ни на этом балконе, вы до меня не доберетесь!",
		"Неужели вы не поняли до сих пор? Глупцы!",
		"...",
		"...",
		"...",
		"Изыдите, черти позорные!",
		"Тёмыч...",
		"Тёмыч...!",
		"Тёмыч: Что...?|B",
		"Лёныч: ТЁМЫЧ!!!|W",
		"Тёмыч: А!",
		"Лёныч, шо? Шо случилось?",
		"Что? Где?",
		"Лёныч: Машина встала.|W|-|PLAY lenich_theme",
		"Тёмыч: А что так?",
		"Лёныч: Че то с шинами или с мотором, не знаю, водитель не сказал.",
		"Одно ясно, мы будем дальше ехать на...",
		"...Метро!",
		"Тёмыч: О, Круть.",
		"(Лёныч обожает метро)|B",
		"(Он даже выбирает между машинистом и милицейским)",
		"(Для него, вероятно, проблемы с тачилой - выгода)",
		"(Ибо на метро едем.)",
		"Лёныч: О, А вот и станция как раз таки!|W",
		"Тёмыч: Если я правильно помню адрес того ДК, где устроили конкурс, то нам проехать надо до вокзальной.",
		"Лёныч: Эта станция - Комунарівська?",
		"Странно, но ведь это должна быть покровская...",
		"Тёмыч: Кто его знает, как эти станции делаются...",
		"Лёныч: А, это же на 'Покровскую' переименовали 'Комунаровскую', как я забыл...?",
		"*Позже*|G",
		"Тёмыч: У, а тут тепло|W",
		"Лёныч: Угу.",
		"Здравствуйте, мне жетон в метро.|W|Fedor default",
		"Тёмыч: Да, мне тоже.",
		"Кассир Фёдор: Да, конечно. 14 гривень.",
		"Угу, держите.",
		"Тёмыч: Что ж, пошли...",
		"*Позже*|G",
		"Лёныч: Что ж, ждём поезд...|W|Lenich default",
		"Тёмыч: Эта и Вокзальная станции на колоннах стоят",
		"Почему остальные станции не на колоннах, а в монотонных плитках?",
		"А почему эта на колоннах, а не в монотонных плитках?",
		"Не соблюли стиль архитекторы, а жаль.",
		"Лёныч: А в Харькове есть огромезная станция с флагом Украины по диагонали растянутым.",
		"Тёмыч: Мы только в Харькове не были...",
		"Лёныч: Угу. Я очень хочу и туда съехать.",
		"Проездиться по каждой станции в том метро!",
		"Блин, жалко что у нас в Украине так мало метрополитенов...",
		"Тёмыч: Опа, а вот и вагончик подъехал!",
		"Диктор: Обережно, двері закриваються.",
		"Лёныч: Ого, уже? Быстрее, забегаем!",
		"*ПОЗЖЕ*|G",
		"",
	]
	dialogue_en = [
		"2018, December 24th, 9 AM|G",
		"Temich: *Yawn*|Y|-|PLAY intro_1",
		"(I woke up at 6 AM)|B",
		"(WHAT FOR?!)",
		"(Whatever)",
		"(Ah, come on, we're at the middle of winter)",
		"(I think that my guitar is freeze- and bulletproof)",
		"(But everyone thinks, for some solid reasons surely, that blizzard wears guitar off quickly)",
		"(If so, why hosting that guitarists contest at this exact moment? Is that some kind of plan to destroy Zaporizhzhya's guitarists' guitars?)",
		"(...At any rate, I don't care very much...)",
		"(My name is Artem Zinets Artemovich, I'm 6-grader at Lyceum No. 99)",
		"(Which is commonly mistaken for ZML#99)",
		"(One of our neighbour schools with almost same name)",
		"(I am guitarist with some *outstanding* skills)",
		"(Not only I can play pieces that're 3 grades above me)",
		"(But I can also--)|B|-|STOP",
		"???: Hello, captain!|W|Lenich default",
		"Temich: Ah, Lenich, hello, long time no see...|W|Lenich default|PLAY lenich_theme",
		"???: How's it going, mate?",
		"Temich: Not bad so far...",
		"Uh, yeah...",
		"(This is Leonid, or Lenich, my friend and a partner)|B",
		"(With whom we play guitars in duet and travel around Ukraine for concerts)",
		"(We've came around numerous cities and won many contests)",
		"(That's why I believe that if one's school life is rich and interesting, then the one's in arts school)",
		"(Anyways, Lenich is a huge fan of militia, just like Egorich, my school friend)",
		"(Although Egorich's more like general army's fan, while Lenich is more specified)",
		"Lenich: So, Temich|W",
		"You look sleepy.",
		"Temich: (But of course...)|B",
		"Lenich: Did you take any time to practice?|W",
		"I didn't do much in these 2 days.",
		"Temich: Well, we had equally *no* time to prepare",
		"So I, as well",
		"*have not* prepared",
		"(Lol)|B",
		"Lenich: I hope that you haven't forgotten your guitar.|W",
		"Temich: Well, I hope that you see this contrabass hanging from my back.",
		"I didn't, absolutely, forgot the most important tool I'd ever need for such occassions",
		"By the way, Lenich",
		"Lenich: M?",
		"Temich: What did you have for breakfast?",
		"Lenich: Eheh, meatballs...!",
		"Temich: With mashed potatoes, I trust?",
		"(I'm not following the original meme's template, not to mention that it sounds awful in English, but whatever)|B",
		"Lenich: And bread!|W",
		"Temich: White one?",
		"Lenich: Nah, that grey one, grey one!",
		"Greeeeeey one!",
		"Temich: (Spare my English)|B",
		"(As well as this not-so-good wannabe-pun)",
		"Temich: Hobana, 'limousine' have finally arrived!|W",
		"Lenich: Weird, the autobus to carry contestants, have arrived,",
		"But Irina Nikolaevna haven't...",
		"Temich: Pray tell, if we're departing for guitarists' contest,",
		"What are dancers doing here?",
		"Lenich: Maybe, it's more like 'arts schools contest' than 'guitarist contest'?",
		"Like, for everybody",
		"Temich: Maybe.",
		"At any rate, all we can do is hop in, so let's hop in",
		"*Later on*|G|-|STOP STOP",
		"Temich: Where is the map leading us?\nLenich: To the Dnipro.|W",
		"Temich: La-la-la\nLenich: La-la-la-la-la-laaaaaaa",
		"Temich: (*sigh* I haven't slept for a week)|B",
		"(Just the day before yesterday, that week ended)",
		"(That week when my cats and teachers were hunting me down)",
		"(Forcing me to not sleep for week)",
		"(I WANT TO TAKE A NAP)",
		"(AAAA)",
		"*hrr*|Y",
		"Lenich: What? Temich! It's not time to fall asleep!|W",
		"Temich: hrr......",
		"1 PM, Temich's dream|B",
		"Temich: Begone, thy fouls!|W",
		"Neither now, neither later on, neither on this exact balcony, you'll never get me!",
		"Haven't you realized that much, fools?",
		"...",
		"...",
		"...",
		"Begone, thy horrid fools!",
		"Temich...",
		"Temich...!",
		"Temich: (Uh, what's going on...?)|B",
		"Lenich: TEMICH!!!|W",
		"Temich: A!",
		"What's happening? Mate, what in the...?",
		"What? Where?",
		"Lenich: Car've stopped.|W|-|PLAY lenich_theme",
		"Temich: Why so?",
		"Lenich: Driver's not sure, it've got something to do with tires or exhaust.",
		"Anyways, one thing for sure, we'll reach our destination by...",
		"...Metro!",
		"Temich: Oh, cool.",
		"(Lenich worships metro)|B",
		"(Worships enough to choose between policeman and metro train driver as his future occupation)",
		"(Looks like he absolutely doesn't mind our bus getting busted.)",
		"(After all, that's metro!)",
		"Lenich: What a perfect timing for a station to come on sight!|W",
		"Temich: If I'm not mistaken, that CH where the contest is being hosted is near Wokzalnaya station",
		"Lenich: 'Komunarivska' station?",
		"Weird, I though it's 'Pokrovska' station...",
		"Temich: Well, who knows how are those station made...",
		"Lenich: Ah, wait, I've almost forgot that 'Pokrovska' have just been renamed from 'Komunarivska'. False alert.",
		"*Later*|G",
		"Temich: Oh, it's warm here|W",
		"Lenich: Absolutely.",
		"Good afternoon, I'd like to buy a metro token|W|Fedor default",
		"Temich: And one for me as well.",
		"Fedor the cashier: Okay, that'll be 14 grivnas for you.",
		"Ah, I see. Here you go.",
		"Temich: Okay, let's go...",
		"*Later*|G",
		"Lenich: So, let's wait for the train...|W|Lenich default",
		"Temich: I wonder, why does this station and 'Wokzalnaya' one are built on these pillars",
		"While the rest of Dnipro metro's stations are made out of monotone plates?",
		"Like, this one could be built with plates as well?",
		"Architect's didn't care much about the style, huh?",
		"Lenich: Oh, by the way, there is a huge ukrainian flag stretched diagonally on one of Kharkiv's stations",
		"Temich: Kharkiv is one of those cities we didn't visit yet",
		"Lenich: I really want to go there...",
		"I'd ride to every station in it's metro!",
		"Damn, if only Ukraine had more cities with metro...",
		"Temich: Yay, the train have finally arrived!",
		"Dictor: Attention, the doors are closing",
		"Lenich: Already? We have no time to waste, then. Hop in!",
		"*Later on*|G",
		"",
	]
	dialogue_uk = [
		"2018, 24 грудня 9:00|G",
		"Тьоха: *Зевок*|Y|-|PLAY intro_1",
		"(Я прокинувся о шостій.)|B",
		"(Якого біса я це зробив?!)",
		"(Як би то не було...)",
		"(До речі, зараз зима, то чому конкурс гитаристів збирають саме зараз?)",
		"(Мені здається, що моя гітара - пулею не пробиваєма та холодом не пробираєма)",
		"(Але усі вважають, авжеж не без підставно, що гітара дуже швидко псується на морозі)",
		"(То якщо це так, то навіщо саме зараз скликати конкурс саме гитаристів? Нібито організатори запланували знищення усіх гитаристів Запору, принаймі їх гітар)",
		"(...До речі...)",
		"(Мене звати Артем Зинець Артемович, я з 6-Г класу Лицею №99)",
		"(Який часто плутають із ЗБЛ№99)",
		"(Школа з майже такою ж назвою така...)",
		"(Я - гітарист з *унікальними* здібностями)",
		"(Я можу грати твори, які визначені для учнів на 3 класи вище за мене)",
		"(А також--)|B|-|STOP",
		"???: Привіт, капітане!|W|Lenich default",
		"Тьоха: А, да, привіт, давно не бачились...|W|Lenich default|PLAY lenich_theme",
		"???: Шо, як справи?",
		"Тьоха: Та норм усьо, здається...",
		"Угу...",
		"(Це - Льонич, мой товариш та напарник з гітари.)|B",
		"(Ми граємо дуетом, разом граємо на змаганнях гітарних у різноманітних містах)",
		"(Ми роз'їздили півкраїни на гастролях...)",
		"(Шкільне життя цікаве лише якщо це музикалка)",
		"(До речі, Льонич - фанат міліції, майже як Єгорич)",
		"(Але Єгорич, перш за все, полюбляє саме збройні сили, тобто армію)",
		"Льонич: Гей, Тьоха|W",
		"Ти шо, не виспався, чи що?",
		"Тьоха: (Ти ба, як вгадав!)|B",
		"Льонич: Чи ти встиг будь-як потренуватися?|W",
		"За ці 2 дні я не смикнув ані струни, майже.",
		"Тьоха: Друже мій, ми мали одно мало часу",
		"То й я жодного разу",
		"Не практикувався.",
		"(Гиг)|B",
		"Льонич: Сподіваюсь, ти гітару не забув?|W",
		"Тьоха: Ця бандура в мене за пазухою висить,",
		"Так шо нє",
		"До речі, Льонич",
		"Льонич: Га?",
		"Тьоха: Що ти мав на сніданок?",
		"Льонич: Ехех, котле-е-ети...",
		"Тьоха: Чи з пюрешкою?",
		"(Ні, цей жарт гарно звучить лише російською...)|B",
		"Льонич: Та з хлібушком...!|W",
		"Тьоха: Біленьким?",
		"Льонич: Ні, сіреееееньким",
		"Сірееееньким!",
		"Тьоха: (То ми дійсно сказилися...)|B",
		"(Жарти за 300...)",
		"Тьоха: Хобана, а ось й лімузин підїхав.|W",
		"Льонич: Автобус, який везти конкурсантів, прицуркував",
		"Але Ірина Миколаївна - ні...",
		"Тьоха: І шо тут танцьористи робять?",
		"Я думав, що це конкурс саме гитаристів?",
		"Льонич: Мабуть, це конкурс школ містецтв.",
		"Для усіх бажаючих, чи щось таке",
		"Тьоха: Мабуть.",
		"Гаразд, застрибуєм...",
		"*Через час*|G|-|STOP STOP",
		"Тьоха: Ми їдьмо, їдьмо до сусіднього села, на дискотекуууууууу\nЛьонич: У Дніпро.|W",
		"Тьоха: Тра-ля-ля\nЛьонич: Тра-ля-ля-ля-ля-ляяяяяяяяя",
		"Тьоха: (Я не спав майже тиждень)|B",
		"(Позавчора, нарешті скінчився той тиждень)",
		"(Коли мої коти збожеволіли й вчителі пішли по мою голову)",
		"(Змушуючи мене не спати ночами)",
		"(Я СПАТИ ХОЧУ!)",
		"(АААААААААА)",
		"*хрр*|Y",
		"Льонич: Тьоха? Не спи. Ау. Тьоха?|W",
		"Тьоха: хрр....",
		"13-а дня. Сон Тьохи|B",
		"Тьоха: Геть звідси, чорти позорні!|W",
		"Ані зараз, ані подалі, ні в цій хаті, до мене ви не доберетеся!",
		"Чи ви й досі не зрозуміли! Чорти!",
		"...",
		"...",
		"...",
		"Геть звідси, Іроди Окаянні!",
		"Тьоха...",
		"Тьоха...!",
		"Тьоха: Шо...?|B",
		"Льонич: Тьоха!!!|W",
		"Тьоха: А!",
		"Льонич, шо? Що трапилось?",
		"Що? Де?",
		"Льонич: Машина заглохла.|W|-|PLAY lenich_theme",
		"Тьоха: Через що?",
		"Льонич: Біс його знає, водій нічого не говорить",
		"Але я можу із впевненістю сказати, що далі ми будемо їхати",
		"...Метром!",
		"Тьоха: О, файно.",
		"(Льонич обожнює метро)|B",
		"(Він навіть, як майбутню професію, обирає або машиніста метро, або міліціонера)",
		"(Я б навіть сказав, що для нього гибла машина - вигодно)",
		"(Бо альтернатива - метро)",
		"Льонич: Як зручно, станція просто поряд!|W",
		"Тьоха: До речі, той ДК, де буде конкурс, поряд з Вокзальною розташований",
		"Льонич: Так, це Комунарівська станція?",
		"Странно, мені здавалося, що це повинна була бути Покровська.",
		"Тьоха: Чорт його знає, як ці станції роблять...",
		"Льонич: А, башня моя дурна, 'Покровська' ж нова назва для Комунарівської",
		"*Пізніше*|G",
		"Тьоха: Ох, а тут тепліше.|W",
		"Льонич: Авжеж",
		"Вітаю, мені жетон на метро.|W|Fedor default",
		"Тьоха: Й мені теж.",
		"Касир Федор: Звісно. 14 гривень.",
		"Агов, тримайте.",
		"Тьоха: То поцуркували ж...",
		"*Пізніше*|G",
		"Льонич: Отже, очікуємо на потяг...|W|Lenich default",
		"Тьоха: Дивно, чому Вокзальна та Покровська на колонах тримаються",
		"Коли решта на пластині єдиній тримається?",
		"Або, чому ця на колонах, а не на пластинах?",
		"Архітектори якось стилю не дотримались",
		"Льонич: А у Харкові є величезна станція з флагом України по диагоналі розтягнутим",
		"Тьоха: Нас лише в Харкові не було",
		"Льонич: Що не гарно, тому що я дуже хочу й туди поїхати.",
		"Та пройтися кожною станцію.",
		"Чому в нашій країні так мало метрополітенів?",
		"Тьоха: О! А ось й наш потяг прицуркував.",
		"Диктор: Обережно, двері зачиняються.",
		"Льонич: Що? Вже зараз? Мерщій у потяг!",
		"*Пізніше*|G",
		"",
	]
	match TranslationServer.get_locale():
		"en":
			dialogue = dialogue_en 
			print("Switching dialogue language to english")
		"ru":
			dialogue = dialogue_ru
			print("Switching dialogue language to russian")
		"uk":
			dialogue = dialogue_uk
			print("Switching dialogue language to ukrainian")

func _process(delta):
	if $DialogueSystem.cur == 51:
		$Background/Tick.start()
		$Background/Path2D.show()
	elif $DialogueSystem.cur == 60:
		$Background.animation = "Countryside"
		$Characters/Lenich.hide()
		$Background.scale = Vector2(1.4,1.4)
		$Background/Path2D.hide()
	elif $DialogueSystem.cur == 71:
		$Background.hide()
	elif $DialogueSystem.cur == 98-14:
		$Background.show()
		$Characters/Lenich.show()
		$Background.scale = Vector2(1.1,1.1)
		$Background.animation = "BeforeMetro"
	elif $DialogueSystem.cur == 118-14:
		$Background.animation = "InMetro"
	elif $DialogueSystem.cur == 140-14:
		get_tree().change_scene("res://scenes/dialogues/prologue/prologue2.tscn")


func _input(event):
	if event is InputEventKey:
		if Input.is_action_just_pressed("ui_up"):
			$DialogueSystem.cur = 50


func _on_Tick_timeout():
	bogdan_pos+=0.1
	if bogdan_pos < 1:
		$Background/Path2D/PathFollow2D.set_unit_offset(bogdan_pos)
		$Background/Path2D/PathFollow2D/Bogdan.scale = Vector2(bogdan_pos,bogdan_pos)
		print("wrooooooooooooom wrooooooooooooom wrooooooooooooooooooooooooooooooooooooom ",bogdan_pos," ",$Background/Path2D/PathFollow2D/Bogdan.scale)
	else:
		$Background/Tick.stop()
		print("beep beep")
